- README.md
add proguard content when building release package and using onUnityMessage. otherwise will raise ClassNotFoundException in Android.
> add proguard tip

- README.md
The ReadMe contains deprecated argument names
onUnityViewCreated --> onUnityCreated
Also I've made the Vuforia wrapper example standalone runnable (By adding a MaterialApp) because it can be confusing that the example itself does not run.
> Fixed argument name in ReadMe

- lib/src/controller.dart
If the user doesn't provide a `silent` value to the `quit` method, an error is thrown (booleans cannot be null).
This changes prevents that value being null by marking it as a required param and asserting if null.
> Prevent null value on quit param

- README.md
- Fix incorrect bullet numbering in Readme under the **Android Platform Only (Manual Steps)** section in the documentation - https://pub.dev/packages/flutter_unity_widget#add-flutter-unity-package-to-unity-project
- Readme file auto-formated during editing as per the .md standards. (Not much change visually)
> Fixed incorrect bullet numbering in Readme.md

- ios/Classes/UnityPlayerUtils.swift
Made the unityDidUnload callback available to obj-c and conform to the expected swift signature, so it could be called by UnityFramework. Removed state handling from unload method as it is now handled in the callback.
> Fix for unityDidUnload callback not firing

- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt
- [issues-429: Hide status bar](https://github.com/juicycleff/flutter-unity-view-widget/issues/429)
- Relate Pull request  before kotlin version: [PR-14: Remove java and UnityPlayer changes to the windowmanager so it can be fully handled by Flutter](https://github.com/juicycleff/flutter-unity-view-widget/pull/14)
> Fix: (Android) issues-429-hide-status-bar

- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityView.kt
This PR will fix #421 
A touch duplicated by inject a touch event to Unity player.
Tested on example project. (rotate/touch a cube)
> fix : [Android] Double touch issue

- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt
in flutter set fullscreen:true Did not take effect， Because UnityPlayerUtils no use FlutterUnityWidgetController options, add setFullscreenEnabled function is useful，it is set UnityPlayerUtils options
> fix  fullscreenEnabled not effective

- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt
This solve part of the bug when using version 4.2.2+ cf screens.
Without fullscreen enabled: with a scaffold (or SafeArea) there is extra space between the AppBar and status bar.
With fullscreen enabled: status bar is not displayed
I'm not confortable enougth with android to fix the full bug but this is enougth in my case.
> fix: Hide status bar on fullscreen android

- lib/src/unity_widget.dart
When I switch enablePlaceholder `true` and `false`. The _onPlatformViewCreated function caught exception. This is the debug and error message
> Fix: Set unity controller - Future already complete

- ios/Classes/UnityPlayerUtils.swift
Added missing call to completed in createPlayer to resolve issue #540 (Blank screen on initializing UnityWidget, iOS)
> Added missing call to completed in createPlayer to resolve issue #540

- lib/src/web/web_unity_widget_controller.dart
There's a typo in `messageUnity ` why message were never received by Unity in index.html
`method` should be named `methodName` regarding to generated index.html for UnityLibrary for Web.
This PR fixes this.
> [fix]: typo in MessageEvent -> method

- lib/src/web/unity_widget.dart
- lib/src/web/web_unity_widget_view.dart
`OnUnityCreated` never worked for Web.
This PR fixes this by start calling _onPlatformViewCreated, If first frame of WebView was created.
Otherwise -> Callback in WebViewX is never called!
> [fix]: OnUnityCreated for web

- lib/src/facade_controller.dart
- lib/src/web/unity_widget.dart
- lib/src/web/web_unity_widget_controller.dart
Several concrete implementations were missing for Web to send messages (`postMessage`) and to initialize properly (`init`).
1. This PR fixes these errors
2. This PR refactored the calls to Unity Web by calling messageUnity for example directly.
After investigating actual Federated-Plugin implementations in the Flutter-Community, the MethodChannels aren't working and not best practise for Federated-Plugins or Plugins like these, where you got an Interface-Class.
This messes with invokeMethod and **invokeMethod wasn't even working for web**.
But I just left the `setMethodCallHandler` for any reason you need it.
But now Web is finally sending and receiving messages with this PR.
> [fix]: missing web concrete implementations

- .all-contributorsrc
- .github/workflows/main.yaml
- CHANGELOG.md
- README.md
- example/lib/screens/simple_screen.dart
- example/unity/DemoApp/Assets/StreamingAssets.meta
- example/unity/DemoApp/Packages/manifest.json
- example/unity/DemoApp/Packages/packages-lock.json
- example/unity/DemoApp/ProjectSettings/ProjectSettings.asset
- example/unity/DemoApp/ProjectSettings/ProjectVersion.txt
- ios/Classes/UnityPlayerUtils.swift
- lib/src/io/device_method.dart
- pubspec.yaml
- test/flutter_unity_widget_test.dart
> feat: bumped to flutter 3.3.0

- ios/Classes/UnityPlayerUtils.swift
There are some casting bugs preventing iOS lifecycle events (didBecomeActive, wilEnterForeground, etc) from reaching unity. This causes two issues:
- OnApplicationPaused() callbacks don't fire in unity
- When the app is backgrounded, Unity does not pause, causing high cpu/battery usage while backgrounded
This patch fixes these casting bugs.
Specifically:
- line 173 fixes an attempted cast of the `.appController()` method itself to the object the method returns. Since the method isn't actually called, nothing is returned and the casting fails.
- lines 202-208 fix an attempted cast of `NSNotification.Name` (an enum) to a `String`. This cast fails and so the code path wiring up the observer is skipped.
> Fixed Unity not receiving lifecycle events from iOS

- README.md
- example/lib/main.dart
- example/lib/menu_screen.dart
- example/lib/screens/api_screen.dart
- example/lib/screens/loader_screen.dart
- example/lib/screens/no_interaction_screen.dart
- example/lib/screens/orientation_screen.dart
- example/lib/screens/simple_screen.dart
- example/pubspec.yaml
- example/test/widget_test.dart
This is the same change as #732, but based on the global_unity_controller feature branch #733 as requested.
In that branch only `api_screen.dart` was already updated for the new API changes, so the other pages might still be outdated.
The example code can't simply be pasted into a modern flutter project. It will show errors, mainly due to null-safety changes.
Given that the plugin supports null-safety from version 4.2.0 (18 months ago), it's safe to update the example.
The last commit is a small cleanup by following most suggestions of flutter_lints.
> [feat global_unity_controller] Update examples to null safety

- example/unity/DemoApp/Assets/FlutterUnityIntegration/Demo/Rotate.cs
When launching the demo on flutter Android you couldn't change the rotation speed
because it was Parsed in such a way that the "0.0" format throwed a
Parsing Error
Now it doesn't :robot:
> fix(Unity Demo): fix setRotatioSpeed float Parsing

- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetController.kt
This removes the white background set in Kotlin, which allows us to experiment with a transparent UnityWidget.
iOS doesn't need any change as this already works.
This should not affect most users, because to see any change you need to both manually configure Unity and adjust the android theme.
See this example of a video widget playing behind Unity to get an idea of the possible results.  
(The video is started on a small delay to show the black flash, which is a flutter bug with AndroidView.)
https://user-images.githubusercontent.com/11444698/203645680-dcb7812d-e0c6-4373-89f3-79d72bf6bc68.mp4
See [https://github.com/juicycleff/flutter-unity-view-widget/issues/190#issuecomment-1296383215](https://github.com/juicycleff/flutter-unity-view-widget/issues/190#issuecomment-1296383215) for more …
> Remove Android's white background color.

- lib/src/web/web_unity_widget_view.dart
- pubspec.yaml
This replaces the [webviewx](https://pub.dev/packages/webviewx) package with [webview_flutter_web](https://pub.dev/packages/webview_flutter_web). These are only used on the web platform.
The webviewx package relies on `webview_flutter: ^2.0.13`, which is currently at `4.0.2`. This causes issues when a different webview is used in an app using a UnityWidget. #738
A workaround was to use dependency overrides in pubspec.yaml.
```
dependency_overrides:
webview_flutter: [VERSION_YOU_NEED]
```
A recent webview_flutter_web update (0.2.2) makes it compatible with the Unity export. 
To make things future-proof, let's change this to a webview that isn't abandoned.
The example project seems to work as expected.
I'd love feedback from anyone using Unity in a web project to see how this performs. …
> Replace the webviewx package with webview_flutter_web.

- example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/Build.cs
The build script adds `-keep class com.unity3d.plugin.* { *; }` to the proguard file.
In most setups this simply works, but in some configurations it gets appended to a line that doesn't end in a line break.
For example in #762
`-dontwarn com.google.android.play.core.tasks.Task-keep class com.unity3d.plugin.* { *; }`
I combined both lines that edit the proguard file to ensure it always add a `\n`.
```diff
-  proguardText = proguardText.Replace("-ignorewarnings", "-keep class com.xraph.plugin.** { *; }\n-ignorewarnings");
-  proguardText += "-keep class com.unity3d.plugin.* { *; }";
+  proguardText = proguardText.Replace("-ignorewarnings", "-keep class com.xraph.plugin.** { *; }\n-keep class com.unity3d.plugin.* { *; }\n-ignorewarnings");
```
> Fix missing line break in proguard-unity.

- example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/Build.cs
- example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/XCodePostBuild.cs
This is based on #554 and is the cause for some white screen issues on iOS.
#595 seems to be a workaround for the bug caused by this.
The `XcodePostBuild.cs` script adds a notification trigger into `\ios\UnityLibrary\Classes\UnityAppController.mm`, which is used by the plugin.
The script searches for `}` to find the end of the `startUnity` function and places additional lines there, which works for older Unity versions like 2019.4.23 or 2020.3.6.
This fails with newer Unity versions because of an if-statement that provides an earlier `}`.
The old and correct way:
```diff
{ // 2020.3.6f1
...
AVAudioSession* audioSession = [AVAudioSession sharedInstance];
[audioSession setActive: YES error: nil];
[audioSession addObserver: self forKeyPath: @"outputVolume" options: 0 context: nil]; …
```
> Fix broken UnityReady trigger in iOS exports.

- example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/XCodePostBuild.cs
Xcode 14 deprecates bitcode, and since today Flutter 3.7 has dropped support for bitcode.
We should disable this setting in the iOS export.
Anyone that still needs it for older projects can simply turn it on again or use an older unitypackage.
> Disable bitcode for Xcode 14.

- README.md
- example/lib/main.dart
- example/lib/menu_screen.dart
- example/lib/screens/api_screen.dart
- example/lib/screens/loader_screen.dart
- example/lib/screens/no_interaction_screen.dart
- example/lib/screens/orientation_screen.dart
- example/lib/screens/simple_screen.dart
- example/pubspec.yaml
- example/test/widget_test.dart
The example code can't simply be pasted into a modern flutter project. It will show errors, mainly due to null-safety changes.
Given that the plugin supports null-safety from version 4.2.0 (18 months ago), it's safe to update the example.
Besides some changes in the UnityWidget parameters, this example project is still compatible all the way back to plugin 4.2.0. 
The last commit is a small cleanup by following most suggestions of flutter_lints.
> Update examples to null safety

- README.md
- example/lib/screens/api_screen.dart
- example/lib/screens/loader_screen.dart
- example/lib/screens/no_interaction_screen.dart
- example/lib/screens/orientation_screen.dart
- example/lib/screens/simple_screen.dart
Web needs a PointerInterceptor to be able to click on any widget on top of the UnityWidget.
However in the way this is used in the examples, all clicks are intercepted and none will ever reach Unity #827.
This is because it is wrapped around a `Positioned`, and will take the full dimensions of the Stack.
This pull request simply moves the PointerInterceptor down in the hierarchy, so that it shrinks in size to fit the widget that needs mouse input
- I also added a note about web compression to the readme, as this issue has popped up in Discord multiple times.
> [Web] Fix PointerInterceptor in examples blocking all clicks.

- example/unity/DemoApp/Assets/FlutterUnityIntegration/Editor/Build.cs
Starting Unity 2023, Unity generates build.gradle with ndkPath which contains the absolute path to the NDK. e.g:
```gradle
android {
ndkPath "/Applications/Unity/Hub/Editor/2023.1.14f1/PlaybackEngines/AndroidPlayer/NDK"
compileSdkVersion 33
buildToolsVersion "32.0.0"
```
This causes the build to fail when tested on a different machine or when the ndk version is defined in the app-level _build.gradle_.
```
* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> NDK is not installed
```
> Remove ndkPath from generated build.gradle

- lib/src/web/web_unity_widget_view.dart
Currently the root path is hardcoded to Url.base.origin which is just the domain, and loses any subdirectory references.
This adds the path - it's slightly more fiddly than I'd like because Url.base.path is incosistent.. if there's a directory it ends with a slash, if there isn't it's completely empty rather than '/'.
> Add support for web base not being on the root

- CHANGELOG.md
- pubspec.yaml
These are the exact changes from the 2022.2.1 release on pub dev, which are missing on the master branch.
> Sync 2022.2.1 from pub.dev

- README.md
- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityActivity.kt
- android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/UnityPlayerUtils.kt
- example/android/app/build.gradle
- example/android/app/src/main/kotlin/com/xraph/plugin/flutter_unity_widget_example/MainActivity.kt
Unity made changes to their AndroidJavaProxy which causes a crash when using certain packages.
This breaks popular Unity plugins like ARFoundation and Google Ads, and likely many more.
Unity expects a `mUnityPlayer` property to exist on the MainActivity, but the FlutterActivity used in Flutter apps doesn't have that property.
This change is found in the following Unity versions (and maybe more):
- 2020.3.46 or higher
- 2021.3.19 - 2021.3.20
- 2022.2.4 - 2022.3.18
For the full description and discussion see https://github.com/juicycleff/flutter-unity-view-widget/issues/836
Example of the error when the app crashes:
```
Non-fatal Exception: java.lang.Exception: AndroidJavaException : java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "mUnityPlayer" in class …
```
> [Android] Fix Unity plugins using the AndroidJavaProxy. (mUnityPlayer error)

- ios/Resources/PrivacyInfo.xcprivacy
- ios/flutter_unity_widget.podspec
Starting May 1 2024, Apple requires apps and some 3rd party frameworks to [include a privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) that documents usage of certains APIs.
##
After both a manual search and running [this scanner](https://github.com/Wooder/ios_17_required_reason_api_scanner), this plugin doesn't appear to be using any of these APIs directly.
However Unity uses multiple and is required to provide these manifests.
These are included in builds and exports as of 2021.3.35f1 and 2022.3.18f1, see the [unity docs](https://docs.unity3d.com/2021.3/Documentation/Manual/apple-privacy-manifest-policy.html).
Just as a precaution, this PR adds an empty manifest for the plugin code.
Providing a …
> Add ios privacy manifest

- README.md
Readme updates, as described in #960
>  Update documentation for ArFoundation and Vuforia. 

- .github/workflows/main.yaml
- test/fake_unity_widget_controllers.dart
- test/flutter_unity_widget_test.dart
The github action 'genopets', that checks all pull requests and commits on master, is still running Flutter 3.3.0.
This will lead to instant rejections when using Flutter or Dart sdk features that surpass this, like here https://github.com/juicycleff/flutter-unity-view-widget/pull/1028.
- I updated the Flutter version to 3.24.5.
- `flutter format` is replaced by `dart format` for compatibility with newer Flutter versions.
- `setMockMethodCallHandler` is replaced in the tests. This is deprected since Flutter 3.9 and will throw warnings in `dart analyze`.
> Chore: Update Flutter version in github action.

- CHANGELOG.md
- android/build.gradle
- example/android/app/build.gradle
- example/android/build.gradle
Updated some values in the outdated build.gradle of the plugin.
The example was updated to match it.
##
* Updated compileSdk to 34.  
The plugin is still at compileSdk 29.
34 is currently the minimum for a project to publish on the Play Store, and that is soon to be 35.
Some errors (like #845, #870) are directly caused by this low sdk.
##
* Updated Java 8 to 11
Unity 2021.3 and 2022.3  [both use Java 11](https://docs.unity3d.com/2022.3/Documentation/Manual/android-supported-dependency-versions.html).
And i'm also getting console warnings about Java 8 like:
```
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete …
```
> Update android compileSdk and Java version.
